version: '3.1'
services:
  frontend:
    container_name: frontend
    image: php:apache
    depends_on:
      - api
    ports:
      - 80:80
    volumes:
      - ./website:/var/www/html
    networks:
      - student_network
    environment:
      - USERNAME=toto
      - PASSWORD=python
  api:
    container_name: api
    image: api-service
    volumes:
      - ./simple_api/student_age.json:/data/student_age.json
    ports:
      - 5000:5000
    networks:
      - student_network
  registry-server:
    container_name: registry-server
    image: registry:2
    restart: always
    ports:
      - 9000:5000
    networks:
      - student_network
  registry-ui:
    container_name: registry-ui
    image: joxit/docker-registry-ui:main
    depends_on:
      - registry-server
    restart: always
    ports:
      - 3000:80
    environment:
      - SINGLE_REGISTRY=true
      - REGISTRY_TITLE=Docker API WebApp
      - DELETE_IMAGES=true
      - SHOW_CONTENT_DIGEST=true
      - NGINX_PROXY_PASS_URL=http://registry-server:5000
      - SHOW_CATALOG_NB_TAGS=true
      - CATALOG_MIN_BRANCHES=1
      - CATALOG_MAX_BRANCHES=1
      - TAGLIST_PAGE_SIZE=100
      - REGISTRY_SECURED=false
      - CATALOG_ELEMENTS_LIMIT=1000
    networks:
      - student_network
networks:
  student_network: